# Generated by Django 4.0.4 on 2022-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=0),
        ),
    ]
