# Generated by Django 4.0.4 on 2022-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_booked_booking_cancelled_booking_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
