# Generated by Django 4.0.4 on 2022-07-07 10:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionforumpost',
            name='discussion_post',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
