# Generated by Django 4.0.4 on 2022-06-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionforumpost',
            name='category',
        ),
        migrations.AddField(
            model_name='discussionforumpost',
            name='categories',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion_forums.category'),
        ),
    ]
