# Generated by Django 4.0.4 on 2022-06-27 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0002_remove_discussionforumpost_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionforumpost',
            old_name='user',
            new_name='author',
        ),
    ]
