# Generated by Django 4.0.4 on 2022-06-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0003_rename_user_discussionforumpost_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussionforumpost',
            old_name='categories',
            new_name='category',
        ),
    ]
