# Generated by Django 4.0.4 on 2022-06-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0004_rename_categories_discussionforumpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionforumpost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion_forums.category'),
        ),
    ]
