# Generated by Django 4.0.4 on 2022-06-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0005_alter_discussionforumpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='latest', max_length=400, unique=True),
        ),
    ]
