# Generated by Django 4.0.4 on 2022-06-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0008_alter_category_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionforumpost',
            name='comments',
            field=models.ManyToManyField(blank=True, to='discussion_forums.comment'),
        ),
    ]
