# Generated by Django 4.0.4 on 2022-06-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0009_discussionforumpost_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='discussionforumpost',
            options={'ordering': ['date_updated']},
        ),
    ]
