# Generated by Django 4.0.4 on 2022-06-27 19:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0011_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discussionforumpost',
            name='discussion_post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
