# Generated by Django 4.0.4 on 2022-06-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0012_alter_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionforumpost',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='discussion_forums.comment'),
        ),
    ]
