# Generated by Django 4.0.4 on 2022-06-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0013_alter_discussionforumpost_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
