# Generated by Django 4.0.4 on 2022-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='groupbooking',
            name='current_no_members',
        ),
        migrations.AddField(
            model_name='groupbooking',
            name='category',
            field=models.CharField(default='category', max_length=100),
        ),
        migrations.AddField(
            model_name='groupbooking',
            name='current_members',
            field=models.IntegerField(default=0),
        ),
    ]
