# Generated by Django 4.0.4 on 2022-06-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_sessions', '0002_category_remove_groupbooking_current_no_members_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
