# Generated by Django 4.0.4 on 2022-06-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion_forums', '0001_initial'),
        ('group_sessions', '0007_remove_groupbooking_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbooking',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discussion_forums.category'),
        ),
    ]
