# Generated by Django 4.0.4 on 2022-08-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_sessions', '0008_alter_groupbooking_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbooking',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
