# Generated by Django 4.0.4 on 2022-04-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_serviceprovider_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='first_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='last_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
