# Generated by Django 4.0.4 on 2022-04-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='about',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='bio',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
