# Generated by Django 4.0.4 on 2022-04-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
