# Generated by Django 4.0.4 on 2022-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_agree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agree',
        ),
        migrations.AddField(
            model_name='client',
            name='client_agree_to_T_and_Cs',
            field=models.BooleanField(default=False),
        ),
    ]
