# Generated by Django 4.0.4 on 2022-04-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_agree_client_client_agree_to_t_and_cs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_agree_to_T_and_Cs',
        ),
    ]
