# Generated by Django 4.0.4 on 2022-05-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_client_client_agree_to_t_and_cs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='last_name',
        ),
    ]
