# Generated by Django 4.0.4 on 2022-06-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_calling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='room_name',
            new_name='event_id',
        ),
        migrations.RenameField(
            model_name='roommember',
            old_name='insession',
            new_name='in_session',
        ),
    ]
