# Generated by Django 4.0.4 on 2022-06-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_calling', '0002_rename_room_name_roommember_event_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomMember',
            new_name='VideoConferenceRoomMember',
        ),
    ]
