# Generated by Django 4.0.4 on 2022-06-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_calling', '0003_rename_roommember_videoconferenceroommember'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=1000)),
                ('room_name', models.CharField(max_length=200)),
                ('insession', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VideoConferenceRoomMember',
        ),
    ]
