# Generated by Django 4.0.4 on 2022-06-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0008_serviceprovider_announcements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='cv_document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
