# Generated by Django 4.0.4 on 2022-07-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0009_serviceprovider_cv_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='cv_document',
        ),
    ]
