# Generated by Django 4.0.4 on 2022-07-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0010_remove_serviceprovider_cv_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='bio',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
