# Generated by Django 4.0.4 on 2022-08-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0011_alter_client_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='user.png', null=True, upload_to='images/profile'),
        ),
    ]
